import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    position: "relative",
  },
  diagonalBg: {
    position: "absolute",
    top: -120, // valor negativo para subir o recorte
    left: 0,
    width: 0,
    height: 0,
    borderBottomWidth: height + 120,
    borderRightWidth: width,
    borderTopWidth: 0,
    borderBottomColor: "#314CB6",
    borderRightColor: "transparent",
    borderTopColor: "transparent",
    zIndex: 0,
    opacity: 1,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 50,
    paddingHorizontal: 20,
    backgroundColor: "transparent",
    marginBottom: 10,
    zIndex: 2,
  },
  backButton: {
    padding: 8,
  },
  menuButton: {
    padding: 8,
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#222",
  },
  scrollContent: {
    alignItems: "center",
    paddingBottom: 30,
    zIndex: 2,
  },
  cardPlano: {
    backgroundColor: "#fff",
    borderRadius: 18,
    paddingVertical: 28,
    paddingHorizontal: 26,
    width: width * 0.93,
    marginTop: 10,
    marginBottom: 22,
    borderWidth: 1.2,
    borderColor: "#314CB6",
    shadowColor: "#314CB6",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 8,
    zIndex: 2,
    overflow: "visible",
  },
  cardPlanoRecorte: {
    position: "absolute",
    left: 0,
    bottom: 0,
    width: 38,
    height: 14,
    backgroundColor: "#314CB6",
    borderBottomLeftRadius: 18,
    borderTopRightRadius: 18,
    zIndex: 3,
  },
  planoAtivo: {
    color: "#4CAF50",
    fontWeight: "bold",
    fontSize: 16,
    marginBottom: 2,
    marginLeft: 2,
    letterSpacing: 0.2,
  },
  nomePlano: {
    color: "#314CB6",
    fontWeight: "bold",
    fontSize: 34,
    marginBottom: 18,
    fontFamily: "monospace",
    textShadowColor: "rgba(49,76,182,0.10)",
    textShadowOffset: { width: 1, height: 2 },
    textShadowRadius: 2,
    letterSpacing: 0.5,
  },
  beneficiosList: {
    marginTop: 12,
    gap: 6,
  },
  beneficioItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    marginLeft: 2,
  },
  beneficioText: {
    marginLeft: 12,
    fontSize: 23,
    color: "#111",
    fontWeight: "bold",
    letterSpacing: 0.1,
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: width * 0.93,
    marginBottom: 18,
    gap: 0,
  },
  infoBox: {
    backgroundColor: "#fff",
    borderRadius: 16,
    paddingVertical: 18,
    paddingHorizontal: 16,
    width: width * 0.44,
    alignItems: "flex-start",
    shadowColor: "#314CB6",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
    borderWidth: 1.2,
    borderColor: "#314CB6",
    marginBottom: 8,
  },
  infoLabel: {
    color: "#888",
    fontSize: 16,
    marginBottom: 4,
    fontWeight: "600",
    marginLeft: 2,
  },
  infoValue: {
    color: "#111",
    fontSize: 24,
    fontWeight: "bold",
    marginLeft: 2,
  },
  renovarButton: {
    marginTop: 30,
    backgroundColor: "#7B97F4",
    borderRadius: 8,
    paddingVertical: 14,
    width: width * 0.8,
    alignItems: "center",
    alignSelf: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  renovarButtonText: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "bold",
    letterSpacing: 0.5,
  },
  // Estilos do Menu Modal
  menuOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
    alignItems: "flex-end",
  },

  menuContent: {
    backgroundColor: "white",
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
    paddingHorizontal: 20,
    paddingVertical: 30,
    width: 250,
    height: "100%",
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },

  menuTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 20,
    textAlign: "center",
  },

  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 15,
    paddingHorizontal: 10,
    borderRadius: 10,
    marginBottom: 5,
  },

  menuItemAtivo: {
    backgroundColor: "#F0F4FF",
  },

  menuItemText: {
    fontSize: 16,
    color: "#333",
    marginLeft: 15,
    fontWeight: "500",
  },

  menuItemTextAtivo: {
    color: "#405CBA",
    fontWeight: "600",
  },
});

export default styles;
