import { StyleSheet } from 'react-native';

const stylesModal = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  overlayTouchable: {
    flex: 1,
  },
  modalContainer: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    width: '100%',
    maxHeight: '50%',
    minHeight: '35%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: -10,
    },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 10,
  },
  modalContent: {
    flex: 1,
  },
  headerModal: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  tituloHeader: {
    fontSize: 24,
    fontWeight: '600',
    color: '#333',
  },
  botaoFechar: {
    padding: 8,
  },
  iconeFechar: {
    fontSize: 32,
    color: '#333',
    fontWeight: '400',
  },
  conteudoContainer: {
    flex: 1,
    paddingHorizontal: 20,
  },
  cardContainer: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 15,
    margin: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  selecaoContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 20,
    paddingBottom: 40,
    paddingHorizontal: 20,
  },
  tituloSelecao: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 25,
    textAlign: 'center',
  },
  subtituloSelecao: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 50,
    lineHeight: 24,
  },
  botaoSelecao: {
    width: '100%',
    borderWidth: 2,
    borderColor: '#405CBA',
    borderRadius: 15,
    paddingVertical: 18,
    paddingHorizontal: 25,
    marginBottom: 20,
    alignItems: 'center',
    backgroundColor: '#fff',
    shadowColor: '#405CBA',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  textoBotaoSelecao: {
    color: '#405CBA',
    fontSize: 18,
    fontWeight: '600',
  },
  conteudoScroll: {
    flex: 1,
    paddingVertical: 25,
    paddingHorizontal: 20,
  },
  logoTopo: {
    width: 36,
    height: 36,
    resizeMode: 'contain',
    alignSelf: 'center',
    marginBottom: 10,
  },
  titulo: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 20,
    textAlign: 'center',
  },
  subtitulo: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginTop: 20,
    marginBottom: 12,
  },
  paragrafo: {
    fontSize: 15,
    color: '#555',
    lineHeight: 22,
    marginBottom: 15,
    textAlign: 'justify',
  },
  itemLista: {
    fontSize: 15,
    color: '#555',
    lineHeight: 22,
    marginBottom: 8,
    paddingLeft: 15,
  },
  botaoConcordarContainer: {
    paddingHorizontal: 20,
    paddingVertical: 25,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  botaoConcordar: {
    backgroundColor: '#405CBA',
    borderRadius: 15,
    paddingVertical: 18,
    alignItems: 'center',
    shadowColor: '#405CBA',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 8,
  },
  textoBotaoConcordar: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
});

export default stylesModal;


